# Generated by Django 5.0.1 on 2024-01-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0010_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assigned_to",
            field=models.CharField(default="", max_length=4096),
        ),
    ]
